package com.kanasuki.game.test.event;

public enum EventType {

    MENU_SCREEN_ON, GAME_SCREEN_ON, LEVEL_SCREEN_ON, CHOOSE_GAME_TYPE_SCREEN_ON, CUSTOMIZER_SCREEN_ON,
    NEXT_LEVEL,
    CUSTOMIZABLE_GAME_ON
}
